language: python

python:
  - "3.10"
  - "3.11"
  - "3.12"

# Cache pip dependencies
cache:
  pip: true
  directories:
    - .pytest_cache
    - .ruff_cache

# Services
services:
  - docker

# Environment variables
env:
  global:
    - PYTHONDONTWRITEBYTECODE=1
    - PYTHONPATH=$TRAVIS_BUILD_DIR

# Install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.lock.txt
  - pip install pytest-cov
  - pip install codecov

# Run tests
script:
  # Run unit tests with coverage
  - pytest --cov=dragonshard --cov-report=xml --cov-report=term-missing
  
  # Run linting
  - ruff check dragonshard/
  
  # Run type checking (if mypy is added later)
  # - mypy dragonshard/

# After success
after_success:
  # Upload coverage to Codecov
  - codecov

# Matrix for different test types
matrix:
  include:
    # Unit tests only (faster)
    - python: "3.12"
      env: TEST_TYPE=unit
      script: pytest dragonshard/tests/test_scanner.py -v
    
    # Docker integration tests (slower, only on latest Python)
    - python: "3.12"
      env: TEST_TYPE=docker
      services:
        - docker
      before_install:
        - docker --version
        - docker-compose --version
      script: |
        # Only run Docker tests if Docker is available
        if command -v docker &> /dev/null; then
          python -m pytest dragonshard/tests/test_docker_scanner.py::TestDockerScanner::test_scan_localhost -v
        else
          echo "Docker not available, skipping Docker tests"
        fi

# Notifications
notifications:
  email: false
  slack:
    secure: ""  # Add your Slack webhook URL here if desired

# Deploy to PyPI (when ready)
# deploy:
#   provider: pypi
#   user: __token__
#   password:
#     secure: ""  # Add your PyPI token here
#   on:
#     tags: true
#     python: "3.12" 