version: '3.8'

services:
  # MySQL database (shared)
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./test-env/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # DVWA (most commonly used)
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - MYSQL_DATABASE=testdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # Vulnerable PHP app (fastest to start)
  vuln-php:
    build:
      context: ./test-env
      dockerfile: Dockerfile.vuln-php
    ports:
      - "8082:80"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 10s

  # OWASP Juice Shop
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # WebGoat
  webgoat:
    image: webgoat/webgoat:latest
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/WebGoat"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # Vulnerable Node.js app
  vuln-node:
    build:
      context: ./test-env
      dockerfile: Dockerfile.vuln-node
    ports:
      - "8083:3000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 10s

  # Vulnerable Python app
  vuln-python:
    build:
      context: ./test-env
      dockerfile: Dockerfile.vuln-python
    ports:
      - "8084:5000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 10s

  # Stress Test Application (Complex Multi-Step Vulnerabilities)
  vuln-stress-test:
    build:
      context: ./test-env
      dockerfile: Dockerfile.vuln-stress-test
    ports:
      - "8085:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=testuser
      - DB_PASS=testpass
      - DB_NAME=testdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      timeout: 15s
      retries: 5
      interval: 10s
      start_period: 15s

volumes:
  mysql_data: 